function contourData = extractContourData(contourMatrix)
    % extractContourData Extracts contour line data from a contour matrix.
    %
    % Syntax:
    %   contourData = extractContourData(contourMatrix)
    %
    % Description:
    %   This function extracts individual contour line data from a contour
    %   matrix, as generated by MATLAB's `contour` or `contourf` functions.
    %   Each contour line is stored as a structure containing its Z-value 
    %   (contour level) and the x and y coordinates of its vertices.
    %
    % Input Arguments:
    %   contourMatrix - (2-by-n numeric array) Matrix containing contour
    %                   lines' data, where the first row indicates x-coordinates
    %                   and the second row indicates y-coordinates. The start
    %                   of each contour line is indicated by its Z-value and 
    %                   the number of vertices in the line.
    %
    % Output:
    %   contourData - (cell array) A cell array where each cell contains a
    %                 structure with fields:
    %                   - Z: The Z-value (height) of the contour line.
    %                   - x: x-coordinates of the contour line vertices.
    %                   - y: y-coordinates of the contour line vertices.
    %
    % Example:
    %   % Generate contour data from sample data
    %   [C, ~] = contour(peaks);
    %   % Extract structured contour information
    %   contourData = extractContourData(C);
    %
    % Notes:
    %   - The function assumes the contour matrix format produced by
    %     MATLAB's `contour` and `contourf`.
    %
    % See also: contour, contourf, struct
    
    % Initialize variables to hold contour information
    contourData = {};
    index = 1;
    
    % Extract contour information
    while index <= size(contourMatrix, 2)
        
        % Get the height of the current contour line
        Z_value = contourMatrix(1, index);
        
        % Get the number of vertices for the current contour line
        N_value = contourMatrix(2, index);
        
        % Extract the vertices for this contour line
        xCoords = contourMatrix(1, index+1:index+N_value);
        yCoords = contourMatrix(2, index+1:index+N_value);
        
        % Store the contour line information
        contourData{end+1} = struct('Z', Z_value, 'x', xCoords, 'y', yCoords);
        
        % Move to the next contour line in the matrix
        index = index + N_value + 1;
    end
end
